// Auto-generated from rights_links.json
window.rightsAudioMap = {
  'حقوق الله': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/pujzbf984wt4.mp3',
  'حق الله الاكبر': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/nb1nh44uabon.mp3',
  'حق النفس': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/ad5g9at4k9mp.mp3',
  'حق اللسان': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/qc03ym6ucuns.mp3',
  'حق السمع': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/gnwweu3e83u6.mp3',
  'حق البصر': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/ofv1sr75fqyn.mp3',
  'حق الرجلين': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/yoqw3yu51kee.mp3',
  'حق اليد': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/rx28u2nhbonz.mp3',
  'حق البطن': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/po09arb24g5t.mp3',
  'حق الفرج': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/vaa8j2o381nv.mp3',
  'حق الصلاة': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/sx537jhj03pz.mp3',
  'حق الصوم': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/zacbjopjbaat.mp3',
  'حق الحج': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/dwekpet3v1w9.mp3',
  'حق الصدقة': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/sf4r53r9rv6x.mp3',
  'حق الهدي': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/adw5sytji1va.mp3',
  'حق سائسك بالسلطان': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/bqno8k385pz3.mp3',
  'حق سائسك بالعلم': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/kua5whfcvz16.mp3',
  'حق سائسك بالملك': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/rch3eta55kw8.mp3',
  'حق الرعية بالسلطان': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/nnvuwcghomvo.mp3',
  'حق الرعية بالعلم': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/py8z0qwga2fw.mp3',
  'حق الزوجة': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/ixrk5ugrge04.mp3',
  'حق الرعية بملك اليمين': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/bp47y6czrk1h.mp3',
  'حق الأم': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/qerpxz75csok.mp3',
  'حق الأب': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/ngssdeq9y8nj.mp3',
  'حق الولد': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/swioym1pkw4b.mp3',
  'حق الأخ': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/xranx9958cgd.mp3',
  'حق المنعم على مولاه': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/znjx9m9fr3b5.mp3',
  'حق المولى الجارية عليه نعمتك': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/hy9zkxsfeapi.mp3',
  'حق ذي المعروف': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/tqkacqr3d7jz.mp3',
  'حق المؤذن': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/zevutjq9dago.mp3',
  'حق الإمام في الصلاة': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/wf4c91j1bubb.mp3',
  'حق الجليس': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/pqwpg1qjrrd9.mp3',
  'حق الجار': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/fzfzkoj4zrey.mp3',
  'حق الصاحب': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/ci12qo63pb1q.mp3',
  'حق الشريك': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/nv91xn2is7a9.mp3',
  'حق المال': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/uey7b5qaorfp.mp3',
  'حق الغريم الطالب': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/drh057wh9ocn.mp3',
  'حق الخليط': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/nkk4g545u0w9.mp3',
  'حق الخصم المدعي عليك': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/avssw9nqsbqw.mp3',
  'حق الخصم المدعى عليه': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/totrng1ddas8.mp3',
  'حق المستشير': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/qiro42akaeqo.mp3',
  'حق المشير': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/yozk560yic6f.mp3',
  'حق المستنصح': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/dho0az2zbcez.mp3',
  'حق الناصح': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/yvbf5teq99wu.mp3',
  'حق الكبير': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/rrnyhp37dhfm.mp3',
  'حق الصغير': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/ft09i13osunt.mp3',
  'حق السائل': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/tegkkwj5t5fw.mp3',
  'حق المسؤول': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/pf6z9grey366.mp3',
  'حق من سرك الله به وعلى يديه': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/vkt502s7uvai.mp3',
  'حق من ساءك القضاء على يديه بقول أو فعل': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/myhxfx2047u0.mp3',
  'حق أهل ملتك عامة': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/surwy49avbi8.mp3',
  'حق أهل الذمة': 'https://shiavoice.com/media/khuteb/resalet_elhuquq/hsrr56ghjpmm.mp3',
};
